graph TD
  subgraph "Modelo de Proceso de Negocios"
    Start --> InputData
    InputData --> Validate
    Validate --> Error en caso de fallo
    Validate --> BusinessLogic en caso de éxito
    BusinessLogic --> OutputResults
    OutputResults --> End
  end

  Start((Inicio))
  InputData(Lectura de Datos)
  Validate(Validar Reglas)  
  BusinessLogic(Procesar Reglas de <br/>Negocio/Lógica)
  OutputResults(Escribir Resultados)
  End((Fin))