graph TD
A[Start] --> B(Show Menu)
B --> C(Get User Input)
C --> D(Create)
D --> E(Read)
E --> F(Update)
F --> G[Exit]

classDef n fill:#F44F3B;class n {
    stroke-width: 3px;
    stroke:#333;
    color: #fff;
}

classDef e fill:#FFDD5D;class e {
    stroke-width: 2px;
    stroke:#333;
}

class C,D,E,F n
class B,G e