graph TD
A[Inicio]-->B(Mostrar menú)
B-->|Opción| C(Crear) || D(Leer) || E(Salir)
C-->H[Obtener ID]-->I[Obtener nombre]-->J[Escribir archivo]-->B
D-->F[Leer archivo]
F-->G[Mostrar registros]-->B
G-->|Fin de archivo| B || M[No hay registros]-->B
E-->B
H-->I
I-->J
J-->B