flowchart TD\n\n   st=>start: Inicio:>Main-Procedure\n   e=>end: Fin:>Stop Run\n   cre=>operation: Crear Registro:>Crear-Registro\n   le=>operation: Leer Registros:>Leer-Registros\n   men=>operation: Mostrar Menu:>Menu-Logica\n\n   st-->men\n   men-->cre\n   men-->le\n   men-->men\n   cre-->men\n   le-->men\n   e-->men